# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1305, 860)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sortLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.sortLineEdit.setObjectName("sortLineEdit")
        self.verticalLayout.addWidget(self.sortLineEdit)
        self.roastingLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.roastingLineEdit.setObjectName("roastingLineEdit")
        self.verticalLayout.addWidget(self.roastingLineEdit)
        self.conditionLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.conditionLineEdit.setObjectName("conditionLineEdit")
        self.verticalLayout.addWidget(self.conditionLineEdit)
        self.tasteDesriptionLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.tasteDesriptionLineEdit.setObjectName("tasteDesriptionLineEdit")
        self.verticalLayout.addWidget(self.tasteDesriptionLineEdit)
        self.costLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.costLineEdit.setObjectName("costLineEdit")
        self.verticalLayout.addWidget(self.costLineEdit)
        self.volumeLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.volumeLineEdit.setObjectName("volumeLineEdit")
        self.verticalLayout.addWidget(self.volumeLineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.saveButton = QtWidgets.QPushButton(parent=Form)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_2.addWidget(self.saveButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveButton.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
